### ISSUE TITLE
Feature request: pass parameters to panel apps

### ISSUE THREAD

**Issue by Trophime** [Hoxbro/panel-multi#2]
Hi,
thanks for your demo app.
It helps me to build a simple dasboard.

Now I would like to pass some extra parameters to the panel app.
It seems that we need to use server_document instead of server_session but
It cannot figure out how to properly do it.

Could you please provide an example of such use?
Best

**Comment by Hoxbro** [comment]
Try to take a look at #3 it is not finished but it is a start.

**Comment by Trophime** [comment]
Thanks a lot. It helped me to get my panel working. :+1
